esphome:
  name: ble-proxy-xiao-${device_id}
  friendly_name: BLE Proxy Xiao ${device_id}
  name_add_mac_suffix: false
  comment: "XIAO ESP32C3 BLE Proxy"

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: esp-idf

logger:

bluetooth_proxy:
  active: true

esp32_ble_tracker:

api:
  encryption:
    key: ${esphpme_encryption_key}

ota:
  password: ${esphome_ota_password}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  ap:
    ssid: "BLE Proxy ${device_id}"
    password: ${fallback_ap_password}

captive_portal:
