substitutions:
  device_id: "01"

esphome:
  name: ble-proxy-xiao-${device_id}
  friendly_name: BLE Proxy Xiao ${device_id}
  name_add_mac_suffix: false
  comment: "XIAO ESP32C3 BLE Proxy"

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: esp-idf

logger:

bluetooth_proxy:
  active: true

esp32_ble_tracker:

api:
  encryption:
    key: !secret esphome_encryption_key

ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "BLE Proxy ${device_id}"
    password: !secret fallback_ap_password

captive_portal:
